/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { totalCount: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "totalCount"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  EventDetailsInput: { // input type
    dateTime?: NexusGenScalars['Date'] | null; // Date
    description?: string | null; // String
    name: string; // String!
    venue?: string | null; // String
  }
  TicketTypeInput: { // input type
    description?: string | null; // String
    fineprint?: string | null; // String
    name: string; // String!
  }
}

export interface NexusGenEnums {
  NetworkEnum: "Nikau"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
}

export interface NexusGenObjects {
  Address: { // root type
    address?: string | null; // ID
    id?: string | null; // ID
  }
  Amount: { // root type
    assest?: NexusGenRootTypes['Assest'] | null; // Assest
    number?: number | null; // Int
  }
  Assest: { // root type
    assestId?: string | null; // ID
    name?: string | null; // String
  }
  CENNZNode: { // root type
    name?: string | null; // String
  }
  CENNZNodeConnection: { // root type
    edges?: Array<NexusGenRootTypes['CENNZNodeEdge'] | null> | null; // [CENNZNodeEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount?: number | null; // Int
  }
  CENNZNodeEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['CENNZNode'] | null; // CENNZNode
  }
  Event: { // root type
    dateTime?: NexusGenScalars['Date'] | null; // Date
    description?: string | null; // String
    name?: string | null; // String
    ticketTypes?: Array<NexusGenRootTypes['TicketType'] | null> | null; // [TicketType]
    venue?: string | null; // String
  }
  Mutation: {};
  Network: { // root type
    name?: string | null; // String
  }
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  Ticket: { // root type
    event?: NexusGenRootTypes['Event'] | null; // Event
    ticketType?: NexusGenRootTypes['TicketType'] | null; // TicketType
  }
  TicketConnection: { // root type
    edges?: Array<NexusGenRootTypes['TicketEdge'] | null> | null; // [TicketEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount?: number | null; // Int
  }
  TicketEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['Ticket'] | null; // Ticket
  }
  TicketStub: { // root type
    name?: string | null; // String
  }
  TicketStubConnection: { // root type
    edges?: Array<NexusGenRootTypes['TicketStubEdge'] | null> | null; // [TicketStubEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount?: number | null; // Int
  }
  TicketStubEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['TicketStub'] | null; // TicketStub
  }
  TicketType: { // root type
    event?: NexusGenRootTypes['Event'] | null; // Event
    name?: string | null; // String
  }
  Transcation: { // root type
    expectedSigningAddress?: string | null; // String
    transcationData?: string | null; // String
  }
  TranscationResult: { // root type
    result?: NexusGenRootTypes['Node'] | null; // Node
  }
}

export interface NexusGenInterfaces {
  Node: NexusGenRootTypes['Address'];
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Address: { // field return type
    address: string | null; // ID
    createEvent: NexusGenRootTypes['Transcation'] | null; // Transcation
    id: string | null; // ID
    sentTo: NexusGenRootTypes['Amount'] | null; // Amount
    ticketStubs: NexusGenRootTypes['TicketStubConnection'] | null; // TicketStubConnection
    tickets: NexusGenRootTypes['TicketConnection'] | null; // TicketConnection
  }
  Amount: { // field return type
    assest: NexusGenRootTypes['Assest'] | null; // Assest
    number: number | null; // Int
  }
  Assest: { // field return type
    assestId: string | null; // ID
    name: string | null; // String
  }
  CENNZNode: { // field return type
    name: string | null; // String
  }
  CENNZNodeConnection: { // field return type
    edges: Array<NexusGenRootTypes['CENNZNodeEdge'] | null> | null; // [CENNZNodeEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount: number | null; // Int
  }
  CENNZNodeEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['CENNZNode'] | null; // CENNZNode
  }
  Event: { // field return type
    createAdditionalTickets: NexusGenRootTypes['Transcation'] | null; // Transcation
    createNewTicketType: NexusGenRootTypes['Transcation'] | null; // Transcation
    dateTime: NexusGenScalars['Date'] | null; // Date
    description: string | null; // String
    name: string | null; // String
    ticketStubs: NexusGenRootTypes['TicketStubConnection'] | null; // TicketStubConnection
    ticketTypes: Array<NexusGenRootTypes['TicketType'] | null> | null; // [TicketType]
    tickets: NexusGenRootTypes['TicketConnection'] | null; // TicketConnection
    venue: string | null; // String
  }
  Mutation: { // field return type
    submitTranscation: NexusGenRootTypes['TranscationResult']; // TranscationResult!
  }
  Network: { // field return type
    address: NexusGenRootTypes['Address'] | null; // Address
    event: NexusGenRootTypes['Event'] | null; // Event
    name: string | null; // String
    nodes: NexusGenRootTypes['CENNZNodeConnection'] | null; // CENNZNodeConnection
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    network: NexusGenRootTypes['Network'] | null; // Network
  }
  Ticket: { // field return type
    createRedeemTranscation: NexusGenRootTypes['Transcation'] | null; // Transcation
    createTransferTranscation: NexusGenRootTypes['Transcation'] | null; // Transcation
    event: NexusGenRootTypes['Event'] | null; // Event
    ticketType: NexusGenRootTypes['TicketType'] | null; // TicketType
  }
  TicketConnection: { // field return type
    edges: Array<NexusGenRootTypes['TicketEdge'] | null> | null; // [TicketEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount: number | null; // Int
  }
  TicketEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Ticket'] | null; // Ticket
  }
  TicketStub: { // field return type
    name: string | null; // String
  }
  TicketStubConnection: { // field return type
    edges: Array<NexusGenRootTypes['TicketStubEdge'] | null> | null; // [TicketStubEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
    totalCount: number | null; // Int
  }
  TicketStubEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['TicketStub'] | null; // TicketStub
  }
  TicketType: { // field return type
    event: NexusGenRootTypes['Event'] | null; // Event
    name: string | null; // String
    tickets: NexusGenRootTypes['TicketConnection'] | null; // TicketConnection
  }
  Transcation: { // field return type
    expectedSigningAddress: string | null; // String
    transcationData: string | null; // String
  }
  TranscationResult: { // field return type
    result: NexusGenRootTypes['Node'] | null; // Node
    status: string | null; // String
  }
  Node: { // field return type
    id: string | null; // ID
  }
}

export interface NexusGenFieldTypeNames {
  Address: { // field return type name
    address: 'ID'
    createEvent: 'Transcation'
    id: 'ID'
    sentTo: 'Amount'
    ticketStubs: 'TicketStubConnection'
    tickets: 'TicketConnection'
  }
  Amount: { // field return type name
    assest: 'Assest'
    number: 'Int'
  }
  Assest: { // field return type name
    assestId: 'ID'
    name: 'String'
  }
  CENNZNode: { // field return type name
    name: 'String'
  }
  CENNZNodeConnection: { // field return type name
    edges: 'CENNZNodeEdge'
    pageInfo: 'PageInfo'
    totalCount: 'Int'
  }
  CENNZNodeEdge: { // field return type name
    cursor: 'String'
    node: 'CENNZNode'
  }
  Event: { // field return type name
    createAdditionalTickets: 'Transcation'
    createNewTicketType: 'Transcation'
    dateTime: 'Date'
    description: 'String'
    name: 'String'
    ticketStubs: 'TicketStubConnection'
    ticketTypes: 'TicketType'
    tickets: 'TicketConnection'
    venue: 'String'
  }
  Mutation: { // field return type name
    submitTranscation: 'TranscationResult'
  }
  Network: { // field return type name
    address: 'Address'
    event: 'Event'
    name: 'String'
    nodes: 'CENNZNodeConnection'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    network: 'Network'
  }
  Ticket: { // field return type name
    createRedeemTranscation: 'Transcation'
    createTransferTranscation: 'Transcation'
    event: 'Event'
    ticketType: 'TicketType'
  }
  TicketConnection: { // field return type name
    edges: 'TicketEdge'
    pageInfo: 'PageInfo'
    totalCount: 'Int'
  }
  TicketEdge: { // field return type name
    cursor: 'String'
    node: 'Ticket'
  }
  TicketStub: { // field return type name
    name: 'String'
  }
  TicketStubConnection: { // field return type name
    edges: 'TicketStubEdge'
    pageInfo: 'PageInfo'
    totalCount: 'Int'
  }
  TicketStubEdge: { // field return type name
    cursor: 'String'
    node: 'TicketStub'
  }
  TicketType: { // field return type name
    event: 'Event'
    name: 'String'
    tickets: 'TicketConnection'
  }
  Transcation: { // field return type name
    expectedSigningAddress: 'String'
    transcationData: 'String'
  }
  TranscationResult: { // field return type name
    result: 'Node'
    status: 'String'
  }
  Node: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  Address: {
    createEvent: { // args
      eventDetails: NexusGenInputs['EventDetailsInput']; // EventDetailsInput!
    }
    sentTo: { // args
      assestId?: string | null; // ID
      to?: string | null; // ID
    }
    ticketStubs: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    tickets: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Event: {
    createAdditionalTickets: { // args
      quantity?: number | null; // Int
      ticketTypeId?: string | null; // String
    }
    createNewTicketType: { // args
      quantity?: number | null; // Int
      ticketType?: NexusGenInputs['TicketTypeInput'] | null; // TicketTypeInput
    }
    ticketStubs: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    tickets: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    submitTranscation: { // args
      signature?: string | null; // String
      transcationData?: string | null; // String
    }
  }
  Network: {
    address: { // args
      address: string; // String!
    }
    event: { // args
      id: string; // String!
    }
    nodes: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Query: {
    network: { // args
      network: NexusGenEnums['NetworkEnum']; // NetworkEnum!
    }
  }
  Ticket: {
    createTransferTranscation: { // args
      toAddress: string; // String!
    }
  }
  TicketType: {
    tickets: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Node: "Address"
}

export interface NexusGenTypeInterfaces {
  Address: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "Node";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}